From bd5c19c02152d2a73d430587cea33b8cd225fa0a Mon Sep 17 00:00:00 2001
From: Michal Simek <michal.simek@xilinx.com>
Date: Wed, 10 Jul 2013 11:14:04 +0200
Subject: [PATCH 1021/1566] remoteproc: zynq: Do not call rproc_put() when
 rproc_alloc() failed

commit  70bb07756d35fb9ba6f63e4d07be9033a3c9abdc from
https://github.com/Xilinx/linux-xlnx.git

rproc_put should be called when rproc_add failed.

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>
---
 drivers/remoteproc/zynq_remoteproc.c |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/drivers/remoteproc/zynq_remoteproc.c b/drivers/remoteproc/zynq_remoteproc.c
index ede3a7d..e41dece 100644
--- a/drivers/remoteproc/zynq_remoteproc.c
+++ b/drivers/remoteproc/zynq_remoteproc.c
@@ -299,7 +299,7 @@ static int __devinit zynq_remoteproc_probe(struct platform_device *pdev)
 				&zynq_rproc_ops, prop, sizeof(struct rproc));
 		if (!local->rproc) {
 			dev_err(&pdev->dev, "rproc allocation failed\n");
-			goto rproc_fault;
+			goto ipi_fault;
 		}
 
 		ret = rproc_add(local->rproc);
-- 
1.7.5.4

